# This is a sample config.yaml file for the python-playground command.
# Copy this to ~/.python-playground/config.yaml and edit it.

# Is readline & tab completion on?
readline: true

# Places to find modules.
pythonpath:
- .
- lib
- tests

# Modules to import by default.
import:
- os
- sys
- re
- yaml
